name: Daily NewsAPI Trend Update

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 0点执行（北京时间早上8点）
  workflow_dispatch:

jobs:
  update-trends:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests googletrans==4.0.0-rc1

      - name: Run fetch script
        run: python trend_fetch_newsapi.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add trend_keywords_output.json
          git commit -m "update trend json by NewsAPI"
          git push
